enum ERRORS {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CITY_NOT_FOUND = 'CITY_NOT_FOUND',
  CITY_ALREADY_EXISTS = 'CITY_ALREADY_EXISTS',
  FILTERS_NOT_FOUND = 'FILTERS_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}

export { ERRORS };
